### ISSUE TITLE
Default admin user unable to login via oxTrust

### ISSUE THREAD

**Issue by iromli** [GluuFederation/containership.io#4]
Given:

- oxAuth inside a container connected to OpenLDAP in another container
- oxTrust inside a container connected to OpenLDAP in another container
- OpenLDAP uses `ldap://0.0.0.0:1636` connection string

Problem:

Default admin user can't login to oxTrust. The message in UI is "Incorrect email or password".

**Comment by iromli** [comment]
Here's a log from `oxauth.log`:

```
2017-06-13 14:57:32,780 TRACE [qtp183264084-12] [org.xdi.oxauth.service.SessionStateService] (SessionStateService.java:565) - Session dn: oxAuthSession
Id=fc2f9faa-f315-4fcb-ba2a-f75fdc90b0d3,ou=session,o=@!35E4.9808.39F0.211F!0001!D1A1.0904,o=gluu
2017-06-13 14:57:32,782 TRACE [qtp183264084-12] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:135) - Authenticating ... (interactive: true, s
kipPassword: false, credentials.username: admin)
2017-06-13 14:57:32,783 TRACE [qtp183264084-12] [org.xdi.oxauth.service.SessionStateService] (SessionStateService.java:224) - Found session_state cooki
e: 'fc2f9faa-f315-4fcb-ba2a-f75fdc90b0d3'
2017-06-13 14:57:32,786 TRACE [qtp183264084-12] [org.xdi.oxauth.service.SessionStateService] (SessionStateService.java:563) - Try to get session by id:
 fc2f9faa-f315-4fcb-ba2a-f75fdc90b0d3 ...
2017-06-13 14:57:32,787 TRACE [qtp183264084-12] [org.xdi.oxauth.service.SessionStateService] (SessionStateService.java:565) - Session dn: oxAuthSession
Id=fc2f9faa-f315-4fcb-ba2a-f75fdc90b0d3,ou=session,o=@!35E4.9808.39F0.211F!0001!D1A1.0904,o=gluu
2017-06-13 14:57:32,788 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:171
) - Executing python 'authenticate' authenticator method
2017-06-13 14:57:32,789 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.AuthenticationService] (AuthenticationService.java:136) - Authenticating user w
ith LDAP: username: 'admin', credentials: '1,120,370,966'
2017-06-13 14:57:32,789 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.AuthenticationService] (AuthenticationService.java:267) - Attempting to find us
erDN by primary key: 'uid' and key value: 'admin', credentials: '1,120,370,966'
2017-06-13 14:57:32,790 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.AuthenticationService] (AuthenticationService.java:353) - Getting user informat
ion from LDAP: attributeName = 'uid', attributeValue = 'admin'
2017-06-13 14:57:32,790 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.AuthenticationService] (AuthenticationService.java:367) - Searching user by att
ributes: '[Attribute [name=uid, values=[admin]]]', baseDn: 'o=gluu'
2017-06-13 14:57:32,795 ERROR [qtp183264084-12] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:176
) - Failed to find entries with baseDN: o=gluu, filter: (&(&(objectClass=top))(&(uid=admin)))
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entries with baseDN: o=gluu, filter: (&(&(objectClass=top))(&(uid=ad
min)))
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:361) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:329) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:325) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:317) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:289) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:270) ~[oxLdap-3.0.1.jar:?]
        at org.xdi.oxauth.service.AuthenticationService.getUserByAttribute(AuthenticationService.java:368) ~[classes/:?]
        at org.xdi.oxauth.service.AuthenticationService.authenticate(AuthenticationService.java:285) ~[classes/:?]
        at org.xdi.oxauth.service.AuthenticationService.externalAuthenticate(AuthenticationService.java:213) ~[classes/:?]
        at org.xdi.oxauth.service.AuthenticationService.authenticate(AuthenticationService.java:145) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.xdi.oxauth.service.AuthenticationService_$$_javassist_seam_44.authenticate(AuthenticationService_$$_javassist_seam_44.java) ~[classes/:?]
        at org.xdi.oxauth.service.UserService.authenticate(UserService.java:74) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.xdi.oxauth.service.UserService_$$_javassist_seam_35.authenticate(UserService_$$_javassist_seam_35.java) ~[classes/:?]
        at org.xdi.oxauth.service.external.internal.InternalDefaultPersonAuthenticationType.authenticate(InternalDefaultPersonAuthenticationType.java:31) ~[classes/:?]
        at org.xdi.oxauth.service.external.ExternalAuthenticationService.executeExternalAuthenticate(ExternalAuthenticationService.java:174) [classes/:?]
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.xdi.oxauth.service.external.ExternalAuthenticationService_$$_javassist_seam_21.executeExternalAuthenticate(ExternalAuthenticationService_$$_javassist_seam_21.java) [classes/:?]
        at org.xdi.oxauth.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:232) [classes/:?]
        at org.xdi.oxauth.auth.Authenticator.authenticateImpl(Authenticator.java:141) [classes/:?]
        at org.xdi.oxauth.auth.Authenticator.authenticate(Authenticator.java:102) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.xdi.oxauth.auth.Authenticator_$$_javassist_seam_43.authenticate(Authenticator_$$_javassist_seam_43.java) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335) [jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
        at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:348) [jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
        at org.jboss.el.parser.AstPropertySuffix.invoke(AstPropertySuffix.java:58) [jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
        at org.jboss.el.parser.AstValue.invoke(AstValue.java:96) [jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
        at org.jboss.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276) [jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [jsf-impl-2.1.28-jbossorg-1.jar:?]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:101) [jsf-impl-2.1.28-jbossorg-1.jar:?]
        at javax.faces.component.UICommand.broadcast(UICommand.java:315) [jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786) [jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251) [jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) [jsf-impl-2.1.28-jbossorg-1.jar:?]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.28-jbossorg-1.jar:?]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) [jsf-impl-2.1.28-jbossorg-1.jar:?]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) [jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.14.v20161028.jar:9.3.14.v20161028]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:249) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:355) ~[oxLdap-3.0.1.jar:?]
        ... 154 more
2017-06-13 14:57:32,799 DEBUG [qtp183264084-12] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:233) - Authentication result for user 'admin'. auth_step: '1', result: 'false', credentials: '1,120,370,966'
2017-06-13 14:57:32,799 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:260) - Executing python 'getApiVersion' authenticator method
2017-06-13 14:57:32,800 INFO  [qtp183264084-12] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:155) - Authentication failed for 'admin'
2017-06-13 14:57:32,807 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:128) - Found 1 entries for client id = @!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14
2017-06-13 14:57:32,807 TRACE [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:186) - Get client from cache by Dn 'inum=@!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14,ou=clients,o=@!35E4.9808.39F0.211F!0001!D1A1.0904,o=gluu'
2017-06-13 14:57:32,808 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:128) - Found 1 entries for client id = @!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14
2017-06-13 14:57:32,809 TRACE [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:186) - Get client from cache by Dn 'inum=@!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14,ou=clients,o=@!35E4.9808.39F0.211F!0001!D1A1.0904,o=gluu'
2017-06-13 14:57:32,810 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:128) - Found 1 entries for client id = @!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14
2017-06-13 14:57:32,810 TRACE [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:186) - Get client from cache by Dn 'inum=@!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14,ou=clients,o=@!35E4.9808.39F0.211F!0001!D1A1.0904,o=gluu'
2017-06-13 14:57:32,811 DEBUG [qtp183264084-12] [org.xdi.oxauth.service.ClientService] (ClientService.java:128) - Found 1 entries for client id = @!35E4.9808.39F0.211F!0001!D1A1.0904!0008!335F.9E14
```

**Comment by iromli** [comment]
Here's `ox-ldap.properties`:

```
bindDN: cn=directory manager,o=gluu
bindPassword: //twzOCIF1g=
servers: 192.168.100.3:1636
useSSL: false
maxconnections: 10

oxauth_ConfigurationEntryDN=ou=oxauth,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu
oxtrust_ConfigurationEntryDN=ou=oxtrust,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu
oxidp_ConfigurationEntryDN=ou=oxidp,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu
oxcas_ConfigurationEntryDN=ou=oxcas,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu
oxasimba_ConfigurationEntryDN=ou=oxasimba,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu
oxpassport_ConfigurationEntryDN=ou=oxpassport,ou=configuration,inum=@!35E4.9808.39F0.211F!0002!C0C1.E095,ou=appliances,o=gluu

certsDir=/etc/certs
confDir=
pythonModulesDir=/opt/gluu/python/libs

binaryAttributes=objectGUID
```

**Comment by iromli** [comment]
The problem is found in `appliance.ldif`. I have workaround for resolving this issue. Closing ...

**Comment by ufo79** [comment]
Hello,

I am having exact same issue, can you please tell me how you resolved it?

Thank you in advance.

**Comment by iromli** [comment]
Hi @ufo79, this issue is fixed. What issue you're facing related to this issue?

**Comment by ufo79** [comment]
Hi @iromli , thanks for your quick answer.
I have exactly the same issue you descibed:
-Oxauth on one VM.
-Oxtrust and OpenLdap on a second VM , listening on the external interface.
- I am having the same exception saying 
Failed to find entries with baseDN: o=gluu, filter: (&(&(objectClass=top))(&(uid=admin)))
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entries with baseDN: o=gluu, filter: (&(&(objectClass=top))(&(uid=ad
min)))

(Gluu version 3.0.2)
Do you remember how you solved it? thanks.

**Comment by iromli** [comment]
The docker-based of Gluu Server doesn't use v3.0.2. You may have using the CE version.

This repo is for discussing issue found in the source code of docker-based Gluu Server.
For better support, you may want to open ticket at our support portal https://support.gluu.org/.

**Comment by ufo79** [comment]
Ok, Thank you.
